#include <ns3/csma-helper.h>
#include "ns3/mobility-module.h"
#include "ns3/nstime.h"
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include "ns3/ipv4-global-routing-helper.h"
#include "ns3/netanim-module.h"

#define TCP_SINK_PORT 9000
#define UDP_SINK_PORT 9001

// Experimental parameters
#define MAX_BULK_BYTES 100000
#define DDOS_RATE "20480kb/s"
#define MAX_SIMULATION_TIME 10.0

// Number of IoT Devices and Bots
#define NUMBER_OF_IOT_DEVICES 5
#define NUMBER_OF_BOTS 10

using namespace ns3;

NS_LOG_COMPONENT_DEFINE("IoTAttackSimulation");

int main(int argc, char *argv[])
{
    CommandLine cmd;
    cmd.Parse(argc, argv);

    Time::SetResolution(Time::NS);
    LogComponentEnable("UdpEchoClientApplication", LOG_LEVEL_INFO);
    LogComponentEnable("UdpEchoServerApplication", LOG_LEVEL_INFO);

    // IoT Devices, Router, and Server
    NodeContainer iotDevices, router, server;
    iotDevices.Create(NUMBER_OF_IOT_DEVICES);
    router.Create(1);
    server.Create(1);

    // Nodes for attack bots
    NodeContainer botNodes;
    botNodes.Create(NUMBER_OF_BOTS);

    // Define the Point-To-Point Links and their Parameters
    PointToPointHelper p2p;
    p2p.SetDeviceAttribute("DataRate", StringValue("100Mbps"));
    p2p.SetChannelAttribute("Delay", StringValue("1ms"));

    // Install the Point-To-Point Connections between Nodes
    NetDeviceContainer deviceContainer[NUMBER_OF_IOT_DEVICES], routerServerLink, botDeviceContainer[NUMBER_OF_BOTS];
    for (int i = 0; i < NUMBER_OF_IOT_DEVICES; ++i)
    {
        deviceContainer[i] = p2p.Install(iotDevices.Get(i), router.Get(0));
    }
    routerServerLink = p2p.Install(router.Get(0), server.Get(0));

    for (int i = 0; i < NUMBER_OF_BOTS; ++i)
    {
        botDeviceContainer[i] = p2p.Install(botNodes.Get(i), router.Get(0));
    }

    // Assign IP to IoT Devices and Bots
    InternetStackHelper stack;
    stack.Install(iotDevices);
    stack.Install(router);
    stack.Install(server);
    stack.Install(botNodes);

    Ipv4AddressHelper ipv4;
    ipv4.SetBase("10.0.0.0", "255.255.255.0");  // Use a larger subnet mask

    Ipv4InterfaceContainer iotInterfaces[NUMBER_OF_IOT_DEVICES], routerServerInterface, botInterfaces[NUMBER_OF_BOTS];
    for (int i = 0; i < NUMBER_OF_IOT_DEVICES; ++i)
    {
        iotInterfaces[i] = ipv4.Assign(deviceContainer[i]);
        ipv4.NewNetwork();  // Move to the next subnet for the next device
    }
    routerServerInterface = ipv4.Assign(routerServerLink);

    ipv4.SetBase("10.1.0.0", "255.255.255.0");  // Start a new subnet for bots
    for (int j = 0; j < NUMBER_OF_BOTS; ++j)
    {
        botInterfaces[j] = ipv4.Assign(botDeviceContainer[j]);
        ipv4.NewNetwork();  // Move to the next subnet for the next bot
    }

    // DDoS Application Behaviour
    OnOffHelper onoff("ns3::UdpSocketFactory", Address(InetSocketAddress(routerServerInterface.GetAddress(1), UDP_SINK_PORT)));
    onoff.SetConstantRate(DataRate(DDOS_RATE));
    onoff.SetAttribute("OnTime", StringValue("ns3::ConstantRandomVariable[Constant=30]"));
    onoff.SetAttribute("OffTime", StringValue("ns3::ConstantRandomVariable[Constant=0]"));
    ApplicationContainer onOffApp[NUMBER_OF_BOTS];

    for (int k = 0; k < NUMBER_OF_BOTS; ++k)
    {
        onOffApp[k] = onoff.Install(botNodes.Get(k));
        onOffApp[k].Start(Seconds(0.0));
        onOffApp[k].Stop(Seconds(MAX_SIMULATION_TIME));
    }

    // Sender Application (Packets generated by this application are throttled)
    BulkSendHelper bulkSend("ns3::TcpSocketFactory", InetSocketAddress(routerServerInterface.GetAddress(1), TCP_SINK_PORT));
    bulkSend.SetAttribute("MaxBytes", UintegerValue(MAX_BULK_BYTES));
    ApplicationContainer bulkSendApp = bulkSend.Install(iotDevices.Get(0)); // IoT Device 0 sends data
    bulkSendApp.Start(Seconds(0.0));
    bulkSendApp.Stop(Seconds(MAX_SIMULATION_TIME - 10));

    // UDP Sink on receiver side (Server)
    PacketSinkHelper UDPsink("ns3::UdpSocketFactory",
                             Address(InetSocketAddress(Ipv4Address::GetAny(), UDP_SINK_PORT)));
    ApplicationContainer UDPSinkApp = UDPsink.Install(server.Get(0));
    UDPSinkApp.Start(Seconds(0.0));
    UDPSinkApp.Stop(Seconds(MAX_SIMULATION_TIME));

    // TCP Sink Application on server side
    PacketSinkHelper TCPsink("ns3::TcpSocketFactory",
                             InetSocketAddress(Ipv4Address::GetAny(), TCP_SINK_PORT));
    ApplicationContainer TCPSinkApp = TCPsink.Install(server.Get(0));
    TCPSinkApp.Start(Seconds(0.0));
    TCPSinkApp.Stop(Seconds(MAX_SIMULATION_TIME));

    Ipv4GlobalRoutingHelper::PopulateRoutingTables();

    // Simulation NetAnim configuration and node placement
    MobilityHelper mobility;

    mobility.SetPositionAllocator("ns3::GridPositionAllocator",
                                  "MinX", DoubleValue(0.0), "MinY", DoubleValue(0.0), "DeltaX", DoubleValue(5.0), "DeltaY", DoubleValue(10.0),
                                  "GridWidth", UintegerValue(5), "LayoutType", StringValue("RowFirst"));

    mobility.SetMobilityModel("ns3::ConstantPositionMobilityModel");

    mobility.Install(iotDevices);
    mobility.Install(router);
    mobility.Install(server);
    mobility.Install(botNodes);

    // Create an AnimationInterface object for XML output
    AnimationInterface anim("IoTAttackSimulation.xml");

    // Enable packet metadata in XML
    anim.EnablePacketMetadata(true);

    // Positioning of nodes
    for (int l = 0; l < NUMBER_OF_IOT_DEVICES; ++l)
    {
        ns3::AnimationInterface::SetConstantPosition(iotDevices.Get(l), l * 5, 0);
    }
    ns3::AnimationInterface::SetConstantPosition(router.Get(0), 15, 10);
    ns3::AnimationInterface::SetConstantPosition(server.Get(0), 25, 10);

    uint32_t x_pos = 0;
    for (int m = 0; m < NUMBER_OF_BOTS; ++m)
    {
        ns3::AnimationInterface::SetConstantPosition(botNodes.Get(m), x_pos++, 20);
    }

    // Run the Simulation
    Simulator::Run();
    Simulator::Destroy();
    return 0;
}
