import xml.etree.ElementTree as ET
import csv
import re

def parse_benign_xml_to_csv(xml_file, csv_file, benign_ip_prefix):
    tree = ET.parse(xml_file)
    root = tree.getroot()

    with open(csv_file, mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(["Timestamp", "Source", "Destination", "PacketSize", "Label"])

        packet_count = 0  # To count the number of packets processed
        benign_count = 0

        for packet in root.findall('.//p'):
            meta_info = packet.get('meta-info')
            if meta_info:
                # Extracting timestamp
                timestamp = packet.get('fbTx', '0')  # fallback to '0' if 'fbTx' not found

                # Extracting source and destination IP addresses
                ip_match = re.search(r'(\d+\.\d+\.\d+\.\d+) > (\d+\.\d+\.\d+\.\d+)', meta_info)
                if ip_match:
                    source_ip = ip_match.group(1)
                    destination_ip = ip_match.group(2)
                else:
                    continue  # skip this packet if IP addresses are not found

                # Extracting packet size
                size_match = re.search(r'length:\s+(\d+)', meta_info)
                packet_size = size_match.group(1) if size_match else '0'

                # Check if it's benign traffic based on source IP
                if source_ip.startswith(benign_ip_prefix):
                    label = "Benign"
                    writer.writerow([timestamp, source_ip, destination_ip, packet_size, label])
                    benign_count += 1

                packet_count += 1

        print(f"Total packets processed: {packet_count}")
        print(f"Total Benign packets: {benign_count}")

def main():
    # Path to the XML file generated by NS-3
    xml_file = r"C:\Users\Shaurya\Downloads\ns3-cybersecurity-simulations\1. NS3.31\ns-allinone-3.31\ns-3.31\BenignTraffic.xml"
    
    # Output CSV file path
    csv_file = 'C:/Users/Shaurya/Downloads/FuzzAIoT/data/BenignTraffic.csv'

    # Define the benign IP prefix based on the simulation setup
    benign_ip_prefix = "10.1.0."  # Prefix for benign source IPs

    # Parse the XML file and convert to CSV
    print("Processing the benign traffic XML...")
    parse_benign_xml_to_csv(xml_file, csv_file, benign_ip_prefix)

    print("Conversion completed. CSV file has been saved.")

if __name__ == "__main__":
    main()
